#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/zheap
#
# IDENTIFICATION
#    src/backend/access/zheap/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/zheap
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = zheapam.o

include $(top_srcdir)/src/backend/common.mk
