#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/undoxacttest
#
# IDENTIFICATION
#    src/backend/access/undoxacttest/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/undoxacttest
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = test.o undoxacttest.o

include $(top_srcdir)/src/backend/common.mk
