#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/foo
#
# IDENTIFICATION
#    src/backend/access/foo/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/foo
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = foo.o

include $(top_srcdir)/src/backend/common.mk
